### PR TITLE
added makemepass.py for hacktoberfest t-shirt

### PR DESCRIPTION
**Pull request by ashkmb**

### CODE REVIEW

**Comment by ashkmb** [comment]
A simple password generator using python.
Cheers

**Comment by hasanmdarif** [comment]
> A simple password generator using python.
> Cheers

Don't make a pr like "for hacktoberfest t-shirt".

**Comment by ashkmb** [comment]
Does replacing the commit message lead to a approved PR ?
@hasanmdarif

**Comment by hasanmdarif** [comment]
> Does replacing the commit message lead to a approved PR ?
> @hasanmdarif

Sure 👍

**Pull request closed without merging**
